PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/pffmod_ace.mk \
    $(LOCAL_DIR)/pffmod_anzu.mk \
    $(LOCAL_DIR)/pffmod_blade.mk \
    $(LOCAL_DIR)/pffmod_bravo.mk \
    $(LOCAL_DIR)/pffmod_bravoc.mk \
    $(LOCAL_DIR)/pffmod_buzz.mk \
    $(LOCAL_DIR)/pffmod_captivatemtd.mk \
    $(LOCAL_DIR)/pffmod_click.mk \
    $(LOCAL_DIR)/pffmod_crespo.mk \
    $(LOCAL_DIR)/pffmod_crespo4g.mk \
    $(LOCAL_DIR)/pffmod_desirec.mk \
    $(LOCAL_DIR)/pffmod_dream_sapphire.mk \
    $(LOCAL_DIR)/pffmod_droid2.mk \
    $(LOCAL_DIR)/pffmod_droid2we.mk \
    $(LOCAL_DIR)/pffmod_encore.mk \
    $(LOCAL_DIR)/pffmod_espresso.mk \
    $(LOCAL_DIR)/pffmod_es209ra.mk \
    $(LOCAL_DIR)/pffmod_fascinatemtd.mk \
    $(LOCAL_DIR)/pffmod_hallon.mk \
    $(LOCAL_DIR)/pffmod_hero.mk \
    $(LOCAL_DIR)/pffmod_heroc.mk \
    $(LOCAL_DIR)/pffmod_inc.mk \
    $(LOCAL_DIR)/pffmod_jordan.mk \
    $(LOCAL_DIR)/pffmod_galaxys2.mk \
    $(LOCAL_DIR)/pffmod_galaxys2att.mk \
    $(LOCAL_DIR)/pffmod_galaxysmtd.mk \
    $(LOCAL_DIR)/pffmod_generic.mk \
    $(LOCAL_DIR)/pffmod_glacier.mk \
    $(LOCAL_DIR)/pffmod_legend.mk \
    $(LOCAL_DIR)/pffmod_leo.mk \
    $(LOCAL_DIR)/pffmod_liberty.mk \
    $(LOCAL_DIR)/pffmod_mango.mk \
    $(LOCAL_DIR)/pffmod_mecha.mk \
    $(LOCAL_DIR)/pffmod_mesmerizemtd.mk \
    $(LOCAL_DIR)/pffmod_mimmi.mk \
    $(LOCAL_DIR)/pffmod_morrison.mk \
    $(LOCAL_DIR)/pffmod_motus.mk \
    $(LOCAL_DIR)/pffmod_one.mk \
    $(LOCAL_DIR)/pffmod_p990.mk \
    $(LOCAL_DIR)/pffmod_p999.mk \
    $(LOCAL_DIR)/pffmod_passion.mk \
    $(LOCAL_DIR)/pffmod_robyn.mk \
    $(LOCAL_DIR)/pffmod_saga.mk \
    $(LOCAL_DIR)/pffmod_shadow.mk \
    $(LOCAL_DIR)/pffmod_shakira.mk \
    $(LOCAL_DIR)/pffmod_sholes.mk \
    $(LOCAL_DIR)/pffmod_showcasemtd.mk \
    $(LOCAL_DIR)/pffmod_smb_a1002.mk \
    $(LOCAL_DIR)/pffmod_smb_a1004.mk \
    $(LOCAL_DIR)/pffmod_smb_a1011.mk \
    $(LOCAL_DIR)/pffmod_smb_b9701.mk \
    $(LOCAL_DIR)/pffmod_smultron.mk \
    $(LOCAL_DIR)/pffmod_speedy.mk \
    $(LOCAL_DIR)/pffmod_supersonic.mk \
    $(LOCAL_DIR)/pffmod_v9.mk \
    $(LOCAL_DIR)/pffmod_u8220.mk \
    $(LOCAL_DIR)/pffmod_urushi.mk \
    $(LOCAL_DIR)/pffmod_vega.mk \
    $(LOCAL_DIR)/pffmod_vibrantmtd.mk \
    $(LOCAL_DIR)/pffmod_vision.mk \
    $(LOCAL_DIR)/pffmod_vivo.mk \
    $(LOCAL_DIR)/pffmod_vivow.mk \
    $(LOCAL_DIR)/pffmod_z71.mk \
    $(LOCAL_DIR)/pffmod_zeppelin.mk \
    $(LOCAL_DIR)/pffmod_zero.mk \
    $(LOCAL_DIR)/pffmod_zeus.mk \
    $(LOCAL_DIR)/pffmod_zeusc.mk
